---
title: "TSA Final Forecasting"
author: "Yinan Ding, Jinxi Liu, Zhengqi Jiao"
date: "2023-04-11"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r, package, message=FALSE, warning=FALSE}
#Load/install required package here
library(lubridate)
library(ggplot2)
library(forecast)  
library(Kendall)
library(tseries)
library(outliers)
library(tidyverse)
library(smooth)
library(kableExtra)
library(dplyr)
library(kableExtra)
```

##Checking working directory
```{r}
getwd()
```

##Import Data

```{r, import data}
library(readxl)
hourlyprice.raw <- read.csv("./Data/Day-Ahead_Zonal_NYC_2018-2022.csv",stringsAsFactors = FALSE) # hourly LBMP of NYC from January 2018 to December 2022
hourlyload.raw <- read.csv("./Data/NYC Load_Forecast_2018-2022.csv",stringsAsFactors = FALSE) # hourly LBMP of NYC from January 2018 to December 2022
NGprice.raw <- read.csv("./Data/Henry_Hub_Natural_Gas_Spot_Price.csv",stringsAsFactors = FALSE) # Daily NG Price from January 2018 to December 2022
REgeneration.raw <- read.csv("./Data/Monthly Renewable Generation_2018-2022.csv",stringsAsFactors = FALSE) # RE generation from January 2018 to December 2022
```

##Data Wrangling - hourly to daily
```{r}
class(hourlyprice.raw$Date)
class(hourlyprice.raw$DAM.Zonal.LBMP)

hourlyprice.raw <- hourlyprice.raw %>%
  separate(Date, into = c("date", "time"), sep = " ") %>%
  separate(time, into = c("hour", "minute"), sep = ":")

hourlyprice <- hourlyprice.raw %>%
  select(date,hour,DAM.Zonal.LBMP) %>%
  rename(Price = DAM.Zonal.LBMP)

  
dailyprice <- hourlyprice %>%
  filter( !is.na(hourlyprice$Price)) %>% 
  group_by(date) %>% # here we left column with minutes out
  summarise( daily_mean_price = mean(Price))

class(dailyprice$date)
dailyprice$date <- as.Date.character(dailyprice$date,format = "%m/%d/l")
            
ggplot(dailyprice, aes(x=date,y=daily_mean_price)) +
  geom_line() +
  ylab("Average Daily Electricity Price in NYC from 2018 to 2022")

```

##Data Wrangling - create ts object
```{r}
dailyprice.ts <- msts(dailyprice$daily_mean_price,
                      seasonal.periods = c(7,365.25),
                      start = c(2018,1,1),
                      end = c(2022,12,31)) 

dailyprice.train.ts <- subset(dailyprice.ts,
                                   end = length(dailyprice.ts)-365) #Jan 1st 2018 to Dec 31st 2021
dailyprice.test.ts <- subset(dailyprice.ts,
                                   start = length(dailyprice.ts)-365) # Jan 1st 2021 to Dec 31st 2022

autoplot(dailyprice.ts)
autoplot (dailyprice.train.ts)
autoplot (dailyprice.test.ts)
```


## Decomposing time series objects
```{r}
decompose.dailyprice.train.ts <- mstl(dailyprice.train.ts)
autoplot(decompose.dailyprice.train.ts)
```


## Exponential Smoothing State Space Model
```{r, ETS Model}
ETS.daily.fc.train <-  stlf(, h=365)
autoplot()

autoplot() +
  autolayer(, series="STL + ETS",PI=FALSE) +
  ylab("")
```

## ARIMA with dynamic harmonic fourier components
```{r, ARIMA with dynamic harmonic fourier components}

```

## TBATS
```{r, TBATS}

```

## Neural Network
```{r, Neural Network}

```

## Checking accuracy of models

```{r}

#Model 1: STL + ETS
ETS_scores <- accuracy(ETS_fit$mean,ts_act_power_daily_test)  

#Model 2: ARIMA + Fourier 
ARIMA_scores <- accuracy(ARIMA_Four_for$mean,ts_act_power_daily_test)

# Model 3:  TBATS 
TBATS_scores <- accuracy(TBATS_for$mean,ts_act_power_daily_test)

# Model 3:  Neural Network 
NN_scores <- accuracy(NN_for$mean,ts_act_power_daily_test)

```

## Compare performance metrics
```{r}
#create data frame
scores <- as.data.frame(
  rbind()
  )
row.names(scores) <- c()

#choose model with lowest RMSE
best_model_index <- which.min(scores[,"RMSE"])
cat("The best model by RMSE is:", row.names(scores[best_model_index,]))                       
```